# Yaml script for Travis-CI

language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - os: linux
      python: 2.7
      env:
      - OPTIONAL_DEPS=1
      - BUILD_DOCS=1
    - os: linux
      python: 2.7
      env:
      - OPTIONAL_DEPS=1
    - os: linux
      python: 2.7
      env:
      - OPTIONAL_DEPS=1
      - PIP_FLAGS="--pre"
    - python: 2.7

install:
  # install required packages
  - pip install --upgrade pip
  - pip install --retries 3 ${PIP_FLAGS} networkx>=2.0 numpy<1.17.0 scipy<1.3.0
  - if [[ "${OPTIONAL_DEPS}" == 1 ]]; then
      pip install --retries 3 ${PIP_FLAGS} pytest>=3.6 pytest-cov roman sphinx<2.0 sphinx_rtd_theme;
    fi
  # install adg
  - printenv PWD
  - pip install .
  # show what's installed
  - python --version
  - pip list

script:
  - if [[ "${BUILD_DOCS}" == 1 ]]; then
      cd doc;
      make html;
      cd ..;
    fi
  - if [[ "${OPTIONAL_DEPS}" == 1 ]]; then
      cd adg/tests;
      source run_test_suite.sh;
      cd ../..;
    fi
